### ISSUE TITLE
考虑一下增添一些角色的旧作和西方曲，以及其他角色的主题曲？（笑）

### ISSUE THREAD

**Issue by Windthunder038** [lightbulb128/touhou-card-player#1]
希望可以增加灵梦，魔理沙，幽香，爱丽丝这四位在旧作和西方中的曲子，包括：
东方封魔录：
恋色Magic
东方梦时空：
东方妖恋谈
                      Dim. Dream
东方幻想乡：
东方妖恋谈
                      少女绮想曲 ～ Capriccio
                      星之器 ～ Casket of Star
                      沉睡的恐怖 ～ Sleeping Terror
                      幽梦 ～ Inanimate Dream
东方怪绮谈：
东方妖恋谈
                      少女绮想曲 ～ Capriccio
                      恋色Magic
                      Dim. Dream
                      星之器 ～ Casket of Star
                      Plastic Mind
                      the Grimoire of Alice
                      沉睡的恐怖 ～ Sleeping Terror
                      幽梦 ～ Inanimate Dream
上海爱丽丝幻乐团公式站：
the Grimoire of Alice
秋霜玉：
二色莲花蝶 ～ Ancients
               魔女们的舞会 ～ Magus
稀翁玉：
樱花之恋塚　～ Flower of Japan
蓬莱人形：
二色莲花蝶　～ Red and White
                  樱花之恋塚　～ Flower of Japan
幺乐团的历史 vol.1：
少女绮想曲 ～ Capriccio
                                  星之器 ～ Casket of Star
                                  沉睡的恐怖 ～ Sleeping Terror
                                  幽梦 ～ Inanimate Dream
幺乐团的历史 vol.2：
Plastic Mind
                                  the Grimoire of Alice
幺乐团的历史 vol.3：
恋色Magic
幺乐团的历史 vol.4：
东方妖恋谈
                                  Dim. Dream
以及以下角色的主题曲：
宇佐见莲子：
少女秘封俱乐部（莲台野夜行）
                      月之妖鸟，化猫之幻（莲台野夜行）
玛艾露贝莉·赫恩：
少女秘封俱乐部（莲台野夜行）
                              魔术师梅莉（莲台野夜行）
                              月之妖鸟，化猫之幻（莲台野夜行）
桑尼米尔克：
妖精大战争 ～ Fairy Wars（妖精大战争、东方三月精（第三季）附属CD2）
                      Sunny Rutile Flection（东方三月精（第一季）附属CD、东方三月精（第二季）附属CD2）
                      赌上性命去恶作剧（妖精大战争、东方三月精（第三季）附属CD3）
露娜切露德：
妖精大战争 ～ Fairy Wars（妖精大战争、东方三月精（第三季）附属CD2）
                      因夜失眠（东方三月精（第一季）附属CD、东方三月精（第二季）附属CD2）
                      赌上性命去恶作剧（妖精大战争、东方三月精（第三季）附属CD3）
斯塔萨菲雅：
妖精大战争 ～ Fairy Wars（妖精大战争、东方三月精（第三季）附属CD2）
                      妖精灿烂的样子（东方三月精（第一季）附属CD、东方三月精（第二季）附属CD2）
                      赌上性命去恶作剧（妖精大战争、东方三月精（第三季）附属CD3）

**Comment by lightbulb128** [comment]
我之前考虑过但是最终结论是没有加密封组（没有官方指定曲子）、旧作人物和三妖精（出版物中的曲子我都没加）。如果想要加上的话建议你自己 fork 然后添加到 public/data.json

**Comment by lightbulb128** [comment]
秘封曲我都是加了的（比如蓬莱人形的曲子）；选定预设里面有
